[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block; report=https://jloh.report-uri.com/r/d/xss/enforce"
    X-Content-Type-Options = "nosniff"
    X-GitHub = "jloh/app.geojs.io"
    X-Made-By = "@itsjloh"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"
    # CSP Policy
    # Inline SHA codes:
    # sha256-OcTeNhH11Pw4Cv0XgqitqUxBYL97kpL3xUsLrY0NKcg= -- gitter include
    # sha256-EzUmxQgSbAoRavXDB/alpwpuB5h7Rxsk7yAXDFapyl8= -- gitter inline CSS sttyles
    # Report only
    # Note: Report only policy doesn't have 'upgrade-insecure-requests' as this does nothing in report-only
    Content-Security-Policy-Report-Only = '''
    default-src 'none' ; 
    script-src 'self' maxcdn.bootstrapcdn.com code.jquery.com cdnjs.cloudflare.com get.geojs.io sidecar.gitter.im 'sha256-OcTeNhH11Pw4Cv0XgqitqUxBYL97kpL3xUsLrY0NKcg='; 
    style-src 'self' maxcdn.bootstrapcdn.com 'sha256-EzUmxQgSbAoRavXDB/alpwpuB5h7Rxsk7yAXDFapyl8='; 
    img-src 'self' data: ; 
    font-src 'none' ; 
    form-action 'self' ; 
    child-src https://gitter.im;
    block-all-mixed-content; 
    report-uri https://jloh.report-uri.com/r/d/csp/reportOnly;'''
    # Live rules -  be careful!
    ##Content-Security-Policy = '''
    ##default-src 'none' ; 
    ##script-src 'self' maxcdn.bootstrapcdn.com code.jquery.com cdnjs.cloudflare.com get.geojs.io sidecar.gitter.im; 
    ##style-src 'self' maxcdn.bootstrapcdn.com; 
    ##img-src 'self' data: ; 
    ##font-src 'none' ; 
    ##form-action 'self' ; 
    ##upgrade-insecure-requests; 
    ##block-all-mixed-content;  
    ##report-uri https://jloh.report-uri.com/r/d/csp/enforce;'''

[[headers]]
  for = "/"
  [headers.values]
    # Preload links
    Link = '''
    </css/main.css?v=1.0.0>; rel=preload; as=style, 
    </js/app.js?v=1.0.0>; rel=preload; as=script, 
    </js/validate-ip.js?v=1.0.0>; rel=preload; as=script'''

[[headers]]
  for = "/s/*"
  [headers.values]
    # Preload links
    Link = '''
    </css/main.css?v=1.0.0>; rel=preload; as=style, 
    </js/app.js?v=1.0.0>; rel=preload; as=script, 
    </js/validate-ip.js?v=1.0.0>; rel=preload; as=script'''

# Redirect everything from /s/ for direct linking
# https://www.netlify.com/docs/redirects/#structured-configuration
[[redirects]]
  from   = "/s/*"
  to     = "/index.html"
  status = 200
  force  = true
